# Site Settings
title: Anudeep Samaiya
email: ""
description: >- # This helps Google understand your page content
  Backend Developer, Data Engineering & DevOps expert based in Bengaluru, India. 
  Specializing in Python, Django, GoLang, and Rust. Passionate about solving 
  problems and open-source collaboration.
baseurl: "anudeepsamaiya"
url: "https://anudeepsamaiya.github.io" # the base hostname & protocol for your site

# Social Links
twitter_username: anudeepsamaiya
github_username:  anudeepsamaiya
linkedin_username: anudeepsamaiya

# Search Engine Verification
# Replace 'YOUR_CODE_HERE' with the code from Google Search Console
google_site_verification: "twVFs_dUxCyldlt-Sif72GezMsXbI0wKJEVTBJ1A22g"

# Build Settings
theme: minima # Or your specific theme name
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Plugin Configuration
twitter:
  username: anudeepsamaiya
  card: summary
logo: /assets/img/profile.png # Update with your actual image path

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
